version: '3'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    volumes:
      - .:/code
    command: bash -c "./docker/wait-for.sh db 5432 && bin/rails s -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:example@db:5432/blog_development
    depends_on:
      - db
